"""init

Revision ID: 1ff7a8950909
Revises: 99d5917742ab
Create Date: 2024-04-06 11:19:26.433980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff7a8950909'
down_revision: Union[str, None] = '99d5917742ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('product_name', sa.String(), nullable=True),
        sa.Column('price', sa.Numeric(10, 2), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('location', sa.String(length=100), nullable=True),
        sa.Column('product_id', sa.String(length=36), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=True, default=0),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warehouse')
    op.drop_table('product')
    # ### end Alembic commands ###

