version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq-data:/var/lib/rabbitmq"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  authentication_service:
    build: ./authentication_service
    ports:
      - "8001:8001"
    depends_on:
      - authentication_database
    env_file: ./authentication_service/.env
    volumes:
      - ./authentication_service:/auth_app



  orders_service:
    build: ./orders_service
    ports:
      - "8002:8002"
    depends_on:
      - orders_database
    env_file: ./orders_service/.env
    volumes:
      - ./orders_service:/order_app


  warehouses_service:
    build: ./warehouses_service
    ports:
      - "8003:8003"
    depends_on:
      - warehouses_database
    env_file: ./warehouses_service/.env
    volumes:
      - ./warehouses_service:/warehouse_app


  delivery_service:
    build: ./delivery_service
    ports:
      - "8004:8004"
    depends_on:
      - delivery_database
    env_file: ./delivery_service/.env
    volumes:
      - ./delivery_service:/delivery_app


  authentication_database:
    image: postgres:latest
    ports:
      - "5431:5432"
    env_file: ./authentication_service/.env_db


  orders_database:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ./orders_service/.env_db

  warehouses_database:
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file: ./warehouses_service/.env_db


  delivery_database:
    image: postgres:latest
    ports:
      - "5434:5432"
    env_file: ./delivery_service/.env_db


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - authentication_service
      - orders_service
      - warehouses_service
      - delivery_service
