version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq-data:/var/lib/rabbitmq"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 5

  authentication_service:
    build: ./authentication_service
    command: uvicorn main:authentication_app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    depends_on:
      - authentication_database
    env_file: ./authentication_service/.env
    volumes:
      - ./authentication_service:/auth_app

  orders_service:
    build: ./orders_service
    command: uvicorn main:order_app --host 0.0.0.0 --port 8002 --reload
    ports:
      - "8002:8002"
    depends_on:
      - orders_database
    env_file: ./orders_service/.env
    volumes:
      - ./orders_service:/order_app


  warehouses_service:
    build: ./warehouses_service
    command: uvicorn main:warehouse_app --host 0.0.0.0 --port 8003 --reload
    ports:
      - "8003:8003"
    depends_on:
      - warehouses_database
    env_file: ./warehouses_service/.env
    volumes:
      - ./warehouses_service:/warehouse_app


  delivery_service:
    build: ./delivery_service
    command: uvicorn main:delivery_app --host 0.0.0.0 --port 8004 --reload
    ports:
      - "8004:8004"
    depends_on:
      - delivery_database

    env_file: ./delivery_service/.env
    volumes:
      - ./delivery_service:/delivery_app


  authentication_database:
    image: postgres:latest
    env_file: ./authentication_service/.env_db
    ports:
      - "65400:5432"
    volumes:
      - postgres_authentication_database:/var/lib/postgresql/data/

  orders_database:
    image: postgres:latest
    env_file: ./orders_service/.env_db
    ports:
      - "65401:5432"
    volumes:
      - postgres_orders_database:/var/lib/postgresql/data/


  warehouses_database:
    image: postgres:latest
    env_file: ./warehouses_service/.env_db
    ports:
      - "65402:5432"
    volumes:
      - postgres_warehouses_database:/var/lib/postgresql/data/


  delivery_database:
    image: postgres:latest
    env_file: ./delivery_service/.env_db
    ports:
      - "65403:5432"
    volumes:
      - postgres_delivery_database:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - authentication_service
      - orders_service
      - warehouses_service
      - delivery_service

volumes:
  postgres_authentication_database:
  postgres_orders_database:
  postgres_warehouses_database:
  postgres_delivery_database: